<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MCKL-7604-T" failures="1" tests="6" name="Test" time="0.135" errors="0" timestamp="2023-03-22T10:20:34 IST">
  <testcase classname="seleniumExamples.TestCase" name="TestCase2" time="0.019"/>
  <testcase classname="seleniumExamples.TestCase" name="Testcase1" time="0.021">
    <skipped/>
  </testcase> <!-- Testcase1 -->
  <testcase classname="seleniumExamples.TestCase" name="Testcase1" time="0.002">
    <skipped/>
  </testcase> <!-- Testcase1 -->
  <testcase classname="seleniumExamples.TestCase" name="Testcase1" time="0.002">
    <skipped/>
  </testcase> <!-- Testcase1 -->
  <testcase classname="seleniumExamples.TestCase" name="Testcase1" time="0.002">
    <skipped/>
  </testcase> <!-- Testcase1 -->
  <testcase classname="seleniumExamples.TestCase" name="Testcase1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at seleniumExamples.TestCase.Testcase1(TestCase.java:9)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- Testcase1 -->
</testsuite> <!-- Test -->
